2023-08-31 16:37:43,029 INFO    MainThread:2507077 [wandb_setup.py:_flush():76] Current SDK version is 0.15.8
2023-08-31 16:37:43,029 INFO    MainThread:2507077 [wandb_setup.py:_flush():76] Configure stats pid to 2507077
2023-08-31 16:37:43,029 INFO    MainThread:2507077 [wandb_setup.py:_flush():76] Loading settings from /home/cv/.config/wandb/settings
2023-08-31 16:37:43,029 INFO    MainThread:2507077 [wandb_setup.py:_flush():76] Loading settings from /home/cv/Documents/KD/CLIPPO/wandb/settings
2023-08-31 16:37:43,029 INFO    MainThread:2507077 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-08-31 16:37:43,029 INFO    MainThread:2507077 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-08-31 16:37:43,029 INFO    MainThread:2507077 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'CLIPPO/train.py', 'program': 'train.py'}
2023-08-31 16:37:43,029 INFO    MainThread:2507077 [wandb_init.py:_log_setup():507] Logging user logs to /home/cv/Documents/KD/CLIPPO/wandb/run-20230831_163743-kroiswpz/logs/debug.log
2023-08-31 16:37:43,029 INFO    MainThread:2507077 [wandb_init.py:_log_setup():508] Logging internal logs to /home/cv/Documents/KD/CLIPPO/wandb/run-20230831_163743-kroiswpz/logs/debug-internal.log
2023-08-31 16:37:43,029 INFO    MainThread:2507077 [wandb_init.py:init():547] calling init triggers
2023-08-31 16:37:43,030 INFO    MainThread:2507077 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.00025, 'architecture': 'CLIPPO', 'dataset': 'MNIST', 'epochs': 10000}
2023-08-31 16:37:43,030 INFO    MainThread:2507077 [wandb_init.py:init():596] starting backend
2023-08-31 16:37:43,030 INFO    MainThread:2507077 [wandb_init.py:init():600] setting up manager
2023-08-31 16:37:43,031 INFO    MainThread:2507077 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-08-31 16:37:43,033 INFO    MainThread:2507077 [wandb_init.py:init():606] backend started and connected
2023-08-31 16:37:43,037 INFO    MainThread:2507077 [wandb_init.py:init():697] updated telemetry
2023-08-31 16:37:43,095 INFO    MainThread:2507077 [wandb_init.py:init():730] communicating run to backend with 60.0 second timeout
2023-08-31 16:37:43,903 ERROR   MainThread:2507077 [wandb_init.py:init():756] encountered error: The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
2023-08-31 16:37:44,193 ERROR   MainThread:2507077 [wandb_init.py:init():1165] The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
Traceback (most recent call last):
  File "/home/cv/anaconda3/envs/clippo/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1147, in init
    run = wi.init()
  File "/home/cv/anaconda3/envs/clippo/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 762, in init
    raise error
wandb.errors.AuthenticationError: The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
2023-08-31 16:37:45,195 WARNING MsgRouterThr:2507077 [router.py:message_loop():77] message_loop has been closed
